# Generated by Django 2.2.3 on 2021-06-02 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Address', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=50)),
                ('State', models.CharField(default='', max_length=50)),
                ('Postal_code', models.IntegerField(default=0)),
                ('Phone_number', models.IntegerField(default=0)),
            ],
        ),
    ]
