# Generated by Django 2.2.3 on 2021-06-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Store', '0003_storeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Storeuser', models.CharField(default='', max_length=50)),
                ('Book', models.CharField(default='', max_length=50)),
                ('Quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
