# Generated by Django 2.2.3 on 2021-06-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Store', '0004_storebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebook',
            name='Author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
